import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { PdfDocument } from "../../../src/lib/edit/document.ts";
import { readAcroForm } from "../../../src/lib/edit/acroform-reader.ts";
import { fillForm } from "../../../src/lib/edit/fill.ts";
import {
  Column,
  Document,
  Page,
  Text,
  TextField,
  renderToBytes,
} from "../../../src/lib/api/index.ts";

// Opening ENCRYPTED PDFs, against files from producers other than ourselves.
//
// This suite exists because the first version of the encryption work was tested only against our own
// output, which proved nothing: every one of these fixtures was generated by PDFKit or react-pdf, and
// between them they cover all four revisions still found in the wild. The measurement that prompted it:
// asked for a password, PDFKit and react-pdf produce 40-bit RC4 by DEFAULT, and AES-256 R5 at best -
// neither can emit the R6 we write, so "we support only R6" meant "we can open nothing but our own".

const PASSWORD = "geheim";
const fixture = (name: string) =>
  new Uint8Array(readFileSync(`tests/fixtures/encrypted/${name}.pdf`));

/** Every revision, and what makes each one different from the others. */
const REVISIONS = [
  { file: "pdfkit-rc4-40", label: "R2, RC4 40-bit (PDFKit's DEFAULT)" },
  { file: "pdfkit-rc4-128", label: "R3, RC4 128-bit" },
  { file: "pdfkit-aes-128", label: "R4, AES-128 with a per-object key" },
  { file: "pdfkit-aes-256-r5", label: "R5, AES-256 (Adobe's withdrawn revision)" },
  { file: "reactpdf-aes-256-r5", label: "R5 from react-pdf, our closest competitor" },
];

describe("PdfDocument.open - foreign encrypted files", () => {
  for (const { file, label } of REVISIONS) {
    it(`opens ${label}`, async () => {
      const doc = await PdfDocument.open(fixture(file), { password: PASSWORD });
      expect(doc.isReadable).toBe(true);

      // Strings decrypt to their real values, umlauts included - a wrong key gives plausible-looking
      // noise, so asserting on the CONTENT is what makes this a test.
      const form = readAcroForm(doc)!;
      expect(form.fields.find((f) => f.name === "full_name")?.value).toBe("Ada Lovelace");
      expect(form.fields.find((f) => f.name === "notes")?.value).toContain("äöüß");

      // ... and so do streams, which travel a different path (deciphered, THEN inflated).
      const kids = doc.lookup(doc.lookup(doc.catalog, "Pages"), "Kids");
      const page = doc.resolve(Array.isArray(kids) ? kids[0] : undefined);
      const contents = doc.lookup(page, "Contents");
      const stream = new TextDecoder("latin1").decode(
        doc.streamData(contents as Parameters<typeof doc.streamData>[0]),
      );
      expect(stream).toContain("BT"); // a text object: this really is a content stream
    });
  }

  it("rejects a wrong password on every revision instead of returning noise", async () => {
    for (const { file } of REVISIONS) {
      await expect(PdfDocument.open(fixture(file), { password: "falsch" })).rejects.toThrow(
        /wrong password/,
      );
    }
  });

  it("asks for the password rather than guessing", async () => {
    await expect(PdfDocument.open(fixture("pdfkit-rc4-40"))).rejects.toThrow(/pass its password/);
  });

  it("leaves an unencrypted document completely alone", async () => {
    const bytes = await renderToBytes(Document([Page({ margin: 56 }, [Text("plain")])]));
    const doc = await PdfDocument.open(bytes);
    expect(doc.isEncrypted).toBe(false);
    expect(doc.isReadable).toBe(true);
  });
});

describe("writing stays modern even though reading is permissive", () => {
  it("our own AES-256 R6 round-trips through our own reader", async () => {
    const bytes = await renderToBytes(
      Document([
        Page({ margin: 56 }, [
          Column([TextField({ name: "iban", value: "DE99 1234 äöü", border: "#888" })]),
        ]),
      ]),
      { encrypt: { userPassword: PASSWORD } },
    );
    const doc = await PdfDocument.open(bytes, { password: PASSWORD });
    expect(readAcroForm(doc)!.fields[0].value).toBe("DE99 1234 äöü");
  });

  it("refuses to WRITE a legacy scheme, even after reading one", async () => {
    // Reading RC4 is a concession to files that already exist. Writing it would hand a user protection
    // we know to be broken, so filling a legacy-encrypted file is refused rather than downgraded.
    await expect(
      fillForm(fixture("pdfkit-rc4-40"), { full_name: "Grace" }, { password: PASSWORD }),
    ).rejects.toThrow(/RC4|obsolete|AES-256/);
  });
});
